# Generated by Django 4.2.1 on 2023-05-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_sprout', '0002_pack_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound',
            name='audio_file',
            field=models.FileField(upload_to='sounds/'),
        ),
    ]
