# Generated by Django 4.2.1 on 2023-06-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_sprout', '0003_alter_sound_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='preview',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
