# Generated by Django 4.2.3 on 2023-07-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_sprout', '0006_transaction_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sound',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
